// Made by Daniel J, Team 4713 :^)
#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, MSServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S3_C1_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int reduceSpeed = 5;

#include "JoystickDriver.c"
task liftTask() {
	while(true) {
		getJoystickSettings(joystick);
		if (abs(joystick.joy1_x1) > 10 || abs(joystick.joy1_x1) > 10) { // if above threshold
			getJoystickSettings(joystick);
			motor[motorE] = (joystick.joy1_x1 / reduceSpeed  ); // lift (using X axis because we only have one controller
			motor[motorG] = (joystick.joy1_x1 / reduceSpeed); // lift // THis motor is negative in the motor and sensor setup
		}

		else { // when below threshold, motors will be powered OFF
			motor[motorE] = 0;
			motor[motorG] = 0;

		}
	}
}
task driveTask()
{
	while(true) {
		getJoystickSettings(joystick);
		if (abs(joystick.joy1_y1) > 25 || abs(joystick.joy1_y2) > 25) { // if above threshold
			motor[motorD] = joystick.joy1_y1;
			motor[motorF] = (joystick.joy1_y2); // This motor is reversed in the motor and sensor setup due to how the motor spins.
		}
		else {
			motor[motorD] = 0;
			motor[motorF] = 0;
		}
	}
}


task brushTask() {
	while(true) {
		getJoystickSettings(joystick);

		bool brushToggle = false; // Brush toggle variable initialized

		if(joy1Btn(7) == 1 && brushToggle == false) { // Button 7 Will make the brush spin forwards

			motor[motorA] = 100;
			motor[motorB] = 100;
			brushToggle = !brushToggle; // Switches state of brush toggle from false to true and true to false
		}

		if(joy1Btn(8) == 1 && brushToggle == false) { // Button 8 will make the brush spin backwards
			motor[motorB] = -100;
			motor[motorA] = -100;
			brushToggle = !brushToggle; // Switches the state of brushToggle var
		}

		if(brushToggle == false) { // Brush Toggle which allows for the Button to be held down to cause brushes to spin, when not held down the '
															// Brushes will be off.
			motor[motorA] = 0;
			motor[motorB] = 0;
		}
	}
}
task ServoTask() {
	while(true)
	{
		getJoystickSettings(joystick);  // Update Buttons and Joysticks
		servo[servo2] = joystick.joy1_x2;
		servo[servo1] = joystick.joy1_x2;

	}
}
task main(){

	waitForStart(); // wait for start of TeleOp phase.
	StartTask(ServoTask); // This starts the Servo Task
	StartTask(brushTask); // Starts the brush task (control with trigger buttons)
	StartTask(driveTask); // Starts the main driving task (control with Y axis
	StartTask(liftTask); // Starts the lift task (control with X axis of Left Stick.
}
